# for gamedata tests, pull files out of the nested repo
fixes:
  - "home/runner/work/avrae/avrae/::avrae/"
  - "avrae/avrae/::avrae/"
# don't add annotations everywhere about coverage pls
github_checks:
  annotations: false
